{-----------------------------------------------------------------------}
{ PROJECT               TVISION TOOLS COLLECTION                        }
{                       FREWARE SOFTWARE                                }
{ LIBRARY               SYSTEM UTILITIES                                }
{ MODULE                TVISION_LIBRARY                                 }
{ FILE NAME             TVTOOLS.PAS                                     }
{ PURPOSE               Different TVision Tools                         }
{ VERSION               0.22                                            }
{ DATE                  16-Mar-96                                       }
{ DESIGN                Begtin Ivan                                     }
{ IMPLEMENTATION        Begtin Ivan                                     }
{ COMPANY               None                                            }
{ COPYRIGHT NOTICE      Copyright (C) 1995-1996, Begtin Ivan            }
{ RESTRICTED RIGHTS     AVAILABLE ONLY FOR FREE DISTRIBUTION,           }
{                       NOT FOR COMMERCIAL PURPOSE                      }
{ COMPUTER              IBM PC or compatible                            }
{ OPERATING SYSTEM      MS/PC-DOS Version 3.30 or higher                }
{ COMPILER              Turbo Pascal Version 7.0                        }
{                       (Borland International Inc.)  or compatible     }
{ ASSEMBLY LANGUAGE     Turbo Assember 3.2 or compatible                }
{ LINKER                Turbo Pascal internal                           }
{ ARGUMENTS                                                             }
{                                                                       }
{                                                                       }
{ RETURN                None                                            }
{ REQUIRES              None                                            }
{ NATURAL LANGUAGE      English Language                                }
{ SECOND LANGUAGE       Russian Language                                }
{ SPECIAL               None                                            }
{ DESCRIPTION           1.                                              }
{                       2.                                              }
{                       3.                                              }
{ REVISION HISTORY     Ivan Begtin (IB)                                 }
{                                                                       }
{                                                                       }
{ THANKS TO            Dmitry Stefankov for style lessons               }
{                      Victor Begtin for first Pascal lessons           }
{-----------------------------------------------------------------------}


UNIT  TvTools;

INTERFACE


CONST
     gcwPackBufferSize = 4096;

PROCEDURE PackStream(VAR Source,Dest: TStream);


IMPLEMENTATION

PROCEDURE PackStream(VAR Source,Dest: TStream);
BEGIN
END;


BEGIN
END.
