{ PROJECT               PSYHOLOGY ORIENTED PROGRAMS                     }
{                       INTERNAL USE SOFTWARE                           }
{ LIBRARY               BASIC PSYHOLOGY LIBRARY                         }
{ MODULE                None                                            }
{ FILE NAME             PSMAIN.PAS                                      }
{ PURPOSE               Different tools for psihology analis.            }
{                                                                       }
{ VERSION               0.01b                                           }
{ DATE                  30-Mar-96                                       }
{ DESIGN                Begtin Ivan                                     }
{ IMPLEMENTATION        Begtin Ivan                                     }
{ COMPANY               None                                            }
{ COPYRIGHT NOTICE      Copyright (C) 1997, Begtin Ivan                 }
{ RESTRICTED RIGHTS     AVAILABLE ONLY FOR FREE DISTRIBUTION,           }
{                       NOT FOR COMMERCIAL PURPOSE                      }
{ COMPUTER              IBM PC or compatible, 386+                      }
{ OPERATING SYSTEM      MS/PC-DOS Version 3.30 or higher                }
{ COMPILER              Turbo Pascal Version 7.0                        }
{                       (Borland International Inc.)  or compatible     }
{ ASSEMBLY LANGUAGE     Turbo Assember 3.2 or compatible                }
{ LINKER                Turbo Pascal internal                           }
{ ARGUMENTS             None                                            }
{ RETURN                None                                            }
{ REQUIRES              None                                            }
{ NATURAL LANGUAGE      Russian Language                                }
{ SECOND LANGUAGE       English Language                                }
{ SPECIAL               Works only on 386+ processors                   }
{ DESCRIPTION                                                           }
{                                                                       }
{                                                                       }
{ REVISION HISTORY                                                      }
{                                                                       }
{-----------------------------------------------------------------------}


Unit PsMain;


interface

Uses TSystem, Objects;







implementation





Begin
End.